# What metrics to evaluate on
metrics:
  - recon_mse
  - dst

# Batch size
batch_size: 64
domain_size: 15
domain_varying: false

# Forcing test/val to .eval()
inference_mode: true

# Learning rate and cosine annealing scheduler
gradient_clip: 5
learning_rate: 1e-3

# KL loss betas
betas:
  um: 0.15
  z0: 1e-2
  kl: 1e-3
  cluster: 1e-3

# How many steps are given for inference and to generate
z_amort: 3
gen_len: 20