dataset: mp
dataset_ver: mixed_
dataset_percent: 1.0

task_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
num_dynamics: 12

# Average likelihood MAE threshold to flag a new task
task_threshold: 7.5

testing_splits:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11